import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import ModalProvider from "@/providers/modal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Application root layout that sets document language, applies global fonts, and composes top-level providers.
 *
 * Renders `children` inside a TRPCReactProvider (with ModalProvider mounted alongside the children), applies Geist fonts and antialiasing to the body, and mounts a global Toaster.
 *
 * @param children - Content to render as the application's main content; placed inside the TRPCReactProvider before the ModalProvider.
 * @returns The root HTML structure (`<html>` and `<body>`) containing the app content and global providers.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCReactProvider>
          {children}
          <ModalProvider />
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}